Description: >
  Template utilizando CodeCommit e ECS.

Parameters:
  ClusterName:
    Type: String
    Description: Digite o nome do Cluster 

  RepoName:
    Type: String
    Description: Nome do repo CodeCommit

  RepositoryBranch:
    Type: String
    Default: master
    Description: Nome da Branch (master)
  
  ContainerMemory:
    Description: Quantidade de memoria reservada para o container
    Type: Number
    Default: 200

  DominioAplicacao:
    Description: Dominio da aplicacao (site.com.br)
    Type: String
    Default: site.com.br,www.site.com.br
  
  ArquivoConfig:
    Description: Arquivo de config a ser montado na raiz /var/www/html (laravel /.env)
    Type: String
    Default: /.env

Resources:

  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepoName

  DeploymentPipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://raw.githubusercontent.com/leoddias/aws-sample-codes/master/continuous-deployment/codecommit/deployment-pipeline.yaml
      Parameters:
        Cluster: !Ref ClusterName
        Service: !GetAtt Service.Outputs.ServiceName
        RepoName: !Ref RepoName
        RepositoryBranch: !Ref RepositoryBranch

  Service:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://raw.githubusercontent.com/leoddias/aws-sample-codes/master/continuous-deployment/codecommit/service.yaml
      Parameters:
        Cluster: !Ref ClusterName
        RepoName: !Ref RepoName
        ContainerMemory: !Ref ContainerMemory
        DominioAplicacao: !Ref DominioAplicacao
        ArquivoConfig: !Ref ArquivoConfig

Outputs:
  PipelineUrl:
    Description: Url gerada para acesso Pipeline criado
    Value: !GetAtt DeploymentPipeline.Outputs.PipelineUrl
