Parameters:
  Cluster:
    Type: String

  RepoName:
    Type: String

  ContainerMemory:
    Type: Number
  
  DominioAplicacao:
    Type: String
  
  ArquivoConfig:
    Type: String

Resources:
  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      DesiredCount: 1
      TaskDefinition: !Ref TaskDefinition

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref RepoName
      ContainerDefinitions:
        - Name: app
          Image: amazon/amazon-ecs-sample
          EntryPoint:
            - /usr/sbin/apache2
            - -D
            - FOREGROUND
          Essential: true
          Memory: !Ref ContainerMemory
          PortMappings:
            - ContainerPort: 80
          DockerLabels:
            traefik.frontend.rule: !Join ['', ['Host:', !Ref DominioAplicacao]]
            traefik.port: ''
          MountPoints: 
            - ContainerPath: !Join ['', ['/var/www/html', !Ref ArquivoConfig]]
              SourceVolume: my-vol
      Volumes:
       -
        Host:
          SourcePath: !Join ['', ['/opt/configs/', !Ref DominioAplicacao, !Ref ArquivoConfig]]
        Name: "my-vol"

Outputs:
  ServiceName:
    Value: !Ref Service
