Parameters:
  Cluster:
    Type: String

  RepoName:
    Type: String

  ContainerMemory:
    Type: Number
  
  DominioAplicacao:
    Type: String
  
  LetsEncryptEmail:
    Type: String

Resources:
  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      DesiredCount: 1
      TaskDefinition: !Ref TaskDefinition

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref RepoName
      ContainerDefinitions:
        - Name: app
          Image: amazon/amazon-ecs-sample
          EntryPoint:
            - /usr/sbin/apache2
            - -D
            - FOREGROUND
          Essential: true
          Memory: !Ref ContainerMemory
          PortMappings:
            - ContainerPort: 80
          Environment:
            - Name: VIRTUAL_HOST
              Value: !Ref DominioAplicacao
            - Name: LETSENCRYPT_HOST             
              Value: !Ref DominioAplicacao
            - Name: LETSENCRYPT_EMAIL
              Value: !Ref LetsEncryptEmail
          MountPoints: 
            - 
              ContainerPath: /var/www/html/.env
              SourceVolume: my-vol
      Volumes:
       -
        Host:
          SourcePath: !Join ['', ['/var/envs/', !Ref DominioAplicacao, '/.env']]
        Name: "my-vol"

Outputs:
  ServiceName:
    Value: !Ref Service
